[//]: # (This file is automatically generated. If you wish to make any changes, please use the JSON files and regenerate this file using the tpframework.)

# Throw Exception

Tags: sast, php, php_v7.4.9

Version: v1.0

## Description

In PHP [Exceptions](https://www.php.net/manual/en/language.exceptions.php) are similar to other languages. An exception can be thrown and caught, try blocks indicate positions in code, where exceptions can occur. This pattern should target throwing an exception

## Overview

| Instances                 | has discovery rule   | discovery method   | rule successfull   |
|---------------------------|----------------------|--------------------|--------------------|
| [1 Instance](#1-instance) | yes                  | joern              | yes                |

## 1 Instance

This instance shows a simple example for throwing and catching an exception.

### Code

```PHP
<?php
function inverse($x,$b) {
    if (!$x) {
        throw new Exception($b);
    }
    return 1/$x;
}

$b = $_GET["p1"]; // source
try {
    inverse(5,$b);
    inverse(0,$b);
} catch (Exception $e) {
    // Message has the input $b, XSS Vulnerability
    echo 'Caught exception: ',  $e->getMessage(), "\n"; // sink
}
```

### Instance Properties

| category   | feature_vs_internal_api   | input_sanitizer   | negative_test_case   | source_and_sink   |
|------------|---------------------------|-------------------|----------------------|-------------------|
| D2         | FEATURE                   | no                | no                   | no                |

<details markdown="1">
<summary>
<b>More</b></summary>

<details markdown="1">
<summary>

### Compile
</summary>

```bash
$_main:
     ; (lines=19, args=0, vars=2, tmps=6)
     ; (before optimizer)
     ; /.../PHP/50_throw_exception/1_instance_50_throw_exception/1_instance_50_throw_exception.php:1-16
     ; return  [] RANGE[0..0]
0000 T2 = FETCH_R (global) string("_GET")
0001 T3 = FETCH_DIM_R T2 string("p1")
0002 ASSIGN CV0($b) T3
0003 INIT_FCALL 2 176 string("inverse")
0004 SEND_VAL int(5) 1
0005 SEND_VAR CV0($b) 2
0006 DO_UCALL
0007 INIT_FCALL 2 176 string("inverse")
0008 SEND_VAL int(0) 1
0009 SEND_VAR CV0($b) 2
0010 DO_UCALL
0011 JMP 0018
0012 CV1($e) = CATCH string("Exception")
0013 ECHO string("Caught exception: ")
0014 INIT_METHOD_CALL 0 CV1($e) string("getMessage")
0015 V7 = DO_FCALL
0016 ECHO V7
0017 ECHO string("
")
0018 RETURN int(1)
EXCEPTION TABLE:
     0003, 0012, -, -

inverse:
     ; (lines=11, args=2, vars=2, tmps=4)
     ; (before optimizer)
     ; /.../PHP/50_throw_exception/1_instance_50_throw_exception/1_instance_50_throw_exception.php:2-7
     ; return  [] RANGE[0..0]
0000 CV0($x) = RECV 1
0001 CV1($b) = RECV 2
0002 T2 = BOOL_NOT CV0($x)
0003 JMPZ T2 0008
0004 V3 = NEW 1 string("Exception")
0005 SEND_VAR_EX CV1($b) 1
0006 DO_FCALL
0007 THROW V3
0008 T5 = DIV int(1) CV0($x)
0009 RETURN T5
0010 RETURN null
LIVE RANGES:
     3: 0005 - 0007 (new)
```

</details>

<details markdown="1">
<summary>

### Discovery
</summary>

The rule searches for a call for `THROW` on opcode level.

```scala
val x50 = (name, "50_throw_exception_iall", cpg.call(".*THROW.*").location.toJson);
```

| discovery method   | expected accuracy   |
|--------------------|---------------------|
| joern              | Perfect             |

</details>

<details markdown="1"open>
<summary>

### Measurement
</summary>

| Tool        | Comm_1   | Comm_2   | phpSAFE   | Progpilot   | RIPS   | WAP   | Ground Truth   |
|-------------|----------|----------|-----------|-------------|--------|-------|----------------|
| 08 Jun 2021 | no       | no       | no        | no          | no     | no    | yes            |
| 22 May 2023 | no       | no       |           |             |        |       | yes            |

</details>

</details>
